### ISSUE TITLE
Shader 2 does not exist

### ISSUE THREAD

**Issue by martykan** [gre/gl-react#121]
I'm trying to run the HelloBlue example React Native, but I get an error, saying "Shader 2 does not exist", even though it is defined, just like in the example.

#### Library versions:

```
gl-react@3.6.0 
gl-react-native@3.6.0 
react@16.0.0-alpha.6
react-native@0.43.3 
```

**Comment by gre** [comment]
Random guess but make sure you don't have twice the library "gl-react" dup.
I think you can see that with `npm ls gl-react`

**Comment by martykan** [comment]
Yes, that was the exact issue. Thanks

**Comment by martykan** [comment]
I have one more problem - when I try to load an image from a URL, I get this error: `uniform t: no loader found for value`

**Comment by martykan** [comment]
@gre Any idea what that could be, please?

**Comment by gre** [comment]
no that's weird. what's the format you are trying to use as texture uniform?

**Comment by kelset** [comment]
I faced the same issue when I tried to do this:

```js
<View style={styles.imageContainer}>
  <Surface style={styles.singleImage}>
    <Amaro>
      https://facebook.github.io/react/img/logo_og.png
    </Amaro>
  </Surface>
  <Text style={styles.baseText}>Amaro</Text>
</View>
```

Instead, to make it work with an image locally, I have to:

```js
<View style={styles.imageContainer}>
  <Surface style={styles.singleImage}>
    <Amaro>
      {resolveAssetSource(require('./images/test.jpg'))}
    </Amaro>
  </Surface>
  <Text style={styles.baseText}>Amaro</Text>
</View>
```

(full code over [here](https://github.com/kelset/react-native-glshaders-testing))

**Comment by martykan** [comment]
@kelset Great, that worked!

**Comment by gre** [comment]
this used to be true in gl-react v2 but it should have been fixed in the v3. ( https://github.com/gre/gl-react/blob/c16cebc165e1e76321b82514b4fe7a9331ba6388/packages/gl-react-native/src/GLImages.js#L39 )

it's unfortunate you still have to do this. the cookbook successful don't need that so i'm not sure what's happening, I'll try to reproduce it.

**Comment by harveyconnor** [comment]
I'm still getting the problem:
Node#1(Saturate#20), uniform t: no loader found for value "https://i.imgur.com/uTP9Xfr.jpg"

**Comment by dorthwein** [comment]
I'm running into this issue as well ;( Both remote and local images.

**Comment by davidcian** [comment]
@dorthwein Thank you so much, good find! Absolutely every type of uri works as long as the format you specified is followed!
