### ISSUE TITLE
gl-react-native: GLImages unload mecanism. using a LRU

### ISSUE THREAD

**Issue by gre** [gre/gl-react#96]
example like https://github.com/shoutem/school/tree/master/LiveInstagram will crashes after 40 s because it will allocate a new image each frame and we never free() the texture cache of GLImages .

one way would be to think the user should be in charge of free() ing stuff. but that's complex when we start "sharing images" across different part (then we need reference counting..etc..) but also user can forget to free things, and it's not very react paradigm friendly^^

so another approach is simply to use a LRU.

need to:

- do the LRU on the JS side. it keeps in memory the latest N images used. for the oldest N+ images, it will call...
- a new unload method in the GLImages native module of both iOS and Android projs – that method will...
- free() in the GLImages.c shared code.

**Comment by gre** [comment]
fixed by https://github.com/gre/gl-react/commit/8de5082d682ccc225b38bed9037ec8e912b71b0e

**Comment by lucasbeef** [comment]
Hi, how do we make use of that ?
I tested like in the LiveInstagram example like
```
<Surface style={{ width, height }}>
    <Saturate {...filter}>
        {{ uri: this.state.path }}
    </Saturate>
</Surface>
```
But I guess it takes a bit more work than that. Anyway, it still crashes after something like 20 pictures.

I'm using :
gl-react@3.16.0-beta.e4f3431c,
gl-react-native@3.15.0

Thanks for this great library BTW !
